### ISSUE TITLE
How to convert the struct into json object ?

### ISSUE THREAD

**Issue by Shravan40** [dropbox/json11#113]
I have a `struct `
```
struct studentDetails {
    string rollNumber, name, department, Icra, subCategory, subCategory2;
    double gpa;
} ;
```
I would like to convert `vector<studentDetails> sData;` into json object. Also ` std::string studentJson = Json(sData).dump();` is not working.

**Comment by artwyman** [comment]
You're looking for much more magic than you're going to find here.  There's no automatic introspection in this library (and I'd doubt whether it's possible to create such a library in C++).  You need to build JSON objects with the fields you want, and give them the names you want, etc.

**Comment by nlohmann** [comment]
@Shravan40 You may want to have a look at [nlohmann/json](https://github.com/nlohmann/json). It allows to define serialization/deserialization code for arbitrary types, see https://github.com/nlohmann/json#arbitrary-types-conversions.

(Note I am the author of nlohmann/json and I am only posting here, because the issue has not been fixed.)

**Comment by Shravan40** [comment]
@nlohmann : Thank you for the information. It seems your's library serves my purpose. I will go through the documentation and try to implement it. In case of queries I will get back to you.
