### ISSUE TITLE
Tag Versioning

### ISSUE THREAD

**Issue by scoopxyz** [dropbox/json11#125]
Hello,

It would be great if this repo could use Tags to track versions :)

**Comment by cdalvaro** [comment]
With a tag versioning or a release version this pull request: [homebrew-core/json11](https://github.com/Homebrew/homebrew-core/pull/30916) could be approved!

**Comment by artwyman** [comment]
I think the core concern here is really just nobody wants to put unnecessary effort into versioning and release process for this repo.  We don't need it at Dropbox, and aren't really changing this repo often, as you point out in the Homebrew thread.  We pin commit hashes on all the external repos we use, which avoids the issue of pulling unexpected changes raised in that thread.  I'm kinda surprised that Homebrew doesn't have the ability to do that and specify versions at the level of their tap config, rather than requiring tags in the repo.

I guess to make things easier on users I wouldn't be averse to simply slapping a 1.0 tag on the latest master.  @j4cbo any thoughts?

**Comment by cdalvaro** [comment]
> We pin commit hashes on all the external repos we use, which avoids the issue of pulling unexpected changes raised in that thread. I'm kinda surprised that Homebrew doesn't have the ability to do that and specify versions at the level of their tap config

Indeed this is what I'm done for the [Homebrew formula](https://github.com/Homebrew/homebrew-core/pull/30916/files/2310de6c80024cdf666c9ce5a541fe137f0108a2#diff-1bb9fd0c582883449274aa1307c42241), but it is not enough, so I need a tag version to fit the requirements.

```ruby
class Json11 < Formula
desc "Tiny JSON library for C++11"
homepage "https://github.com/dropbox/json11"
url "https://github.com/dropbox/json11.git", :revision => "ec4e45219af1d7cde3d58b49ed762376fccf1ace"
version "1.0.0"
```

Your proposal of slapping a 1.0 tag to the latest master is OK for me!

**Comment by cdalvaro** [comment]
So, there will finally be a 1.0.0 tag?

**Comment by j4cbo** [comment]
Just added one!
