### ISSUE TITLE
Type conversion operators

### ISSUE THREAD

**Issue by saur0n** [dropbox/json11#44]
Why there are no ``operator int()``, ``operator std::string()``, ``operator bool()`` and others in ``Json`` class?

**Comment by Amleto** [comment]
Certainly I can see operator bool() being confusing/ambiguous.

**Comment by saur0n** [comment]
There is possibility to declare these operators explicit.

**Comment by j4cbo** [comment]
There's no `operator bool` because there's no obvious meaning for it. Javascript's semantics for truthiness are somewhat subtle (e.g. an empty string evaluates as false, but an empty array evaluates as true) and that's often a source of confusion. Being more explicit with `is_null()`, `bool_value()`, etc. makes code easier to read and write.

**Comment by j4cbo** [comment]
Er, replace "no obvious meaning" with "too many possible meanings" in the above

**Comment by saur0n** [comment]
But what about other operators (``operator int()``, ``operator std::string()`` etc)?
