### ISSUE TITLE
UTF8 string input not supported

### ISSUE THREAD

**Issue by szatmary** [dropbox/json11#67]
json.org specifies a  "A string is a sequence of zero or more Unicode characters" I have always taken that to mean utf8. parse_string() does not seem to handle multi byte utf8. I will be happy to do the work and provide a pull request, If its agreed that utf8 support is desirable.

**Comment by j4cbo** [comment]
Is there a particular bug you're seeing? json11 is intended to handle UTF8 properly throughout, which is *usually* transparent, but not in a few cases:
- This is not specified by the JSON standard, but some browsers require \u2028 and \u2029 to be escaped: https://github.com/dropbox/json11/blob/8452587160c5e767cbc2cd49453f03a2e38c50d2/json11.cpp#L90-L97
- JSON only provides \uXXXX escapes, which can't encode characters outside the BMP. The recommendation is to use surrogate pairs (UTF-16), so we need to pay special attention during decode in order to produce valid UTF-8 instead of CESU-8: https://github.com/dropbox/json11/blob/8452587160c5e767cbc2cd49453f03a2e38c50d2/json11.cpp#L520-L534

**Comment by szatmary** [comment]
Yeah, I may have jumped the gun there and imprudently blamed json11, Still investigating. but will close this in the mean time.
